---
- {include_tasks: setup.yml, tags: [setup]}
- {include_tasks: readyness.yml, tags: [readyness]}
- include_tasks: restrict_api.yml
  when: corpusops_rancher_vbox_auth.status == 200
  tags: [restrict_api]
- {include_tasks: want_api.yml, tags: [want_api]}
- include_tasks: agent.yml
  when: corpusops_rancher_vbox_auth.status == 200
  tags: [agent]
- {include_tasks: download_bins.yml, tags: [download_bins]}
#- {debug: msg: "{{vars}}"; failed_when: True}
