---
- name: when until rancher server is ready
  uri:
    url: "{{corpusops_rancher_vbox_vars.url}}"
  register: corpusops_rancher_vbox_ready
  retries: "{{corpusops_rancher_vbox_vars.retries}}"
  delay: 1
  until: corpusops_rancher_vbox_ready.status != -1
  failed_when: corpusops_rancher_vbox_ready.status == -1
  tags: [readyness]
- include_tasks: test_auth.yml
  vars:
    api_user: "{{omit}}"
    api_pw: "{{omit}}"
  tags: [readyness]
