---
- include_tasks: get_secret_variable.yml
  vars:
    secret_path: "{{corpusops_rancher_vbox_cfg}}"
  with_items:
    - corpusops_rancher_vbox_password
    - corpusops_rancher_vbox_api_v
    - corpusops_rancher_vbox_api_k
  no_log: "{{corpusops_rancher_vbox_no_log}}"
- include_role: {name: corpusops.roles/vars_registry}
  vars:
    cops_vars_registry_target: corpusops_rancher_vbox
  tags: [vars]
  no_log: "{{corpusops_rancher_vbox_no_log}}"
- copy:
    dest: "{{corpusops_rancher_vbox_cfg}}/rancher_env"
    mode: "0600"
    content: |
      #!/usr/bin/env bash
      #
      export DOCKER_HOST="tcp://{{corpusops_rancher_vbox_vars.localaddr}}:2375"
      #
      export RANCHER_URL="{{corpusops_rancher_vbox_vars.url}}"
      #
      export RANCHER_ADMIN="{{corpusops_rancher_vbox_vars.admin}}"
      export RANCHER_PASSWORD="{{corpusops_rancher_vbox_vars.password}}"
      #
      export RANCHER_ACCESS_KEY="{{corpusops_rancher_vbox_vars.api_v}}"
      export RANCHER_SECRET_KEY="{{corpusops_rancher_vbox_vars.api_k}}"
  tags: [config]
  no_log: "{{corpusops_rancher_vbox_no_log}}"
